version: '3'

services:
  web:
    container_name: web
    hostname: web
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=SIGENU_EaD
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  db:
    container_name: db
    hostname: db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=SIGENU_EaD
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=gabrielpga20@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5050:80"
    depends_on:
      - db